# Generated by Django 2.2.4 on 2019-08-07 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_auto_20190807_0249'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='completed_at',
            field=models.DateField(blank=True, default=None),
        ),
    ]
